### PR TITLE
Updated Travis config to use ant

### PR DESCRIPTION
**Pull request by TheLastBanana**

### CODE REVIEW

**Comment by kdbanman** [comment]
Anyone have a problem with merging?  @ryant26 , you're using gradle right now.  Will this mess with you?

**Comment by ryant26** [comment]
Nope wont cause any issues for me.

**Comment by TheLastBanana** [comment]
Hm... Something broke, but it was working on my end. One moment.

**Comment by TheLastBanana** [comment]
Interesting. I wonder what Travis is doing differently that made that break it. In any case, I think this is ready to merge.

**Pull request merged**
