### PR TITLE
Initial model from UML

### PR DESCRIPTION
**Pull request by kuzi117**
This is nearly a direct transcription of the v1.1 UML with minor changes (largest probably being all ArrayLists are now wrapped) that can be seen in the v1.2 UML include in this PR.

### CODE REVIEW

**Comment by TheLastBanana** [comment]
Does this work?

**Comment by kdbanman** [comment]
What is the status on this PR?  If a review is still pertinent:

### 1

> Every ArrayList here is actually inside of a wrapper that delegates to the ArrayList.

I know I originally recommended this, but I think raw ArrayLists actually makes sense here. Our lists aren't list-like. They *are* lists.  More importantly, though, any special data or behavior is probably best put in the classes that hold the lists - User holds List<Claim> and Claim holds List<Item>

### 2

> Claimant should include a list of Claims. Currently there's no connection between the two classes.

@TheLastBanana's right.

### 3

> Should be specify that e.g. items is actually a list of UUIDs? Or is it more clear to keep our UML at a conceptual level and say that Claim technically "contains" Items?

A couple things here.  First, I think going a bit deeper than concept is valuable here - we should show *how* we're implementing the parent-child relationship in the UML.  Second, as per point 4 of [this comment](https://github.com/CMPUT301W15T07/TravelTracker/issues/24#issuecomment-75183378), the membership UUID should go on the "many side" of the many to one relationship.  e.g.  Claim should not have a list of Items *or* Item UUIDs.  Rather, Item should know its parent Claim UUID.  This might seem a bit cumbersome, but remember that we're retrieving model objects strictly through the DataSource, so asking a Claim for its Items directly breaks that convention.

**Comment by TheLastBanana** [comment]
We should merge the UML change, but not the code changes since that's going to conflict with all of Ryan's code. Maybe it would make sense for @kuzi117 to make a separate pull request with just the UML?

**Comment by kdbanman** [comment]
Makes sense to me.

**Comment by therabidsquirel** [comment]
I'd also like to point out if we should have a Currency.java in the model or not. We could implement it as an enum like we did for other fields, given we only have to support 7 currencies.

If we want functionality from java.util.currency, we could still implement that outside of the enum.

**Comment by kdbanman** [comment]
There's been some scattered discussion on currency.  I don't know if consensus has been reached, but our UML and skeleton code should probably reflect some sort of choice.  Here's my proposition.  Currency isn't wrapped - util is used directly.  An enum is used to support only selected currencies.

```java
import java.util.Currency;

public enum CurrencyEnum {

	AUD("AUD"),
	CAD("CAD"),
	EUR("EUR"),
	GBP("GBP"),
	USD("USD");
	
	private String codeString;
	
	CurrencyAdapterEnum(String codeString) {
		this.codeString = codeString;
	}

	public Currency getCurrency() {
		Currency.getInstance(codeString);
	}
	
	@Override
	public String toString() {
		return codeString;
	}

}
```

**Comment by ryant26** [comment]
Enum is cool with me, because we will need either an enum or a string array to build the UI spinner. Using the Currency class won't really save us any work.

**Comment by TheLastBanana** [comment]
That's a good idea. That way we can keep the features of java.util.Currency, but "filter" it through our own enum.

**Comment by therabidsquirel** [comment]
@kdbanman That's what I was thinking, except having the Currency.getInstance() called outside of the enum. Having it as a method getCurrency() makes much more sense though.

**Comment by TheLastBanana** [comment]
Grabbed the UML diagram changes. The rest of this was already implemented by Ryan.

**Pull request closed without merging**
